@startuml

class Main {
    + main(String[] args)
}

class Crawler {
    - Webpage startingWebpage

    + Crawler(Webpage webpage)
}

class Webpage {
    - String title
    - String URL
    - Document document

    + getTitle()
    + getURL()
    + getDocument()
}

Main --> Crawler
Crawler <-- Webpage

hide Main fields

@enduml